### ISSUE TITLE
importData.sh fails on docker stack using docker-ce 19.03.5

### ISSUE THREAD

**Issue by oldluke92** [OkieOth/tile_server#3]
The importData shell script fails if using docker stack on docker-ce 19.03.5 because the default network of a stack is not attachable.

Fix:
Adding

```
networks:
  default:
    driver: overlay
    attachable: true
```
to the stack yaml. Got no idea what this does to docker-compose though.
